version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - Sudo yum update
      - sudo amazon-linux-extras -y install nginx1.12 
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
